### ISSUE TITLE
Tic-Tac-Four 

### ISSUE THREAD

**Issue by iG0tB0lts** [jacklul/inlinegamesbot#15]
This isn’t an issue with the code, but the game itself. Sorry if I’m wasting your time on this and you can delete the issue.

I’ve noticed if you get to start, there’s a move that always results in a win. Is the game flawed? I could play you to show you such move.

**Comment by jacklul** [comment]
Tic-tac-toe has also such move I believe

@DO97

**Comment by iG0tB0lts** [comment]
The regular tic tac toe? There is a move, however if 'O' knows what to do it'll end in a draw. In tic-tac-four however, there is no chance to block the win. We can play if you want, contact me on https://t.me/t1k1taka

However if the game is flawed it's still much more fun than the regular tic-tac-toe before you find the unbeatable(I think) move. You can go ahead and close the issue.
P.S:- Great job on inlinegamesbot by the way, me and my friends regularly play Connect 4 😁🙌

**Comment by jacklul** [comment]
@iG0tB0lts Tic-tac-four actually was contributed by @DO97, any ideas on fixing the flaw ? Because there isn't one most likely ...

**Comment by DO97** [comment]
Yes, it is similar to the Tic-Tac-Toe case.
Maybe a smaller grid (6×5 or 5×5) could be better?

A "secret": the same applies to connect four. These are games that with a specific set of moves will end in a predetermined way.

P.S. I'm very glad that you are enjoying this variant of Tic-Tac-Toe. Have you tried Rock Paper Scissors Lizard Spock? @iG0tB0lts

**Comment by iG0tB0lts** [comment]
I think a smaller grid might work, yeah.

Hadn't known Lizard Spock was added, tried it today, great addition.

**Comment by Hunter1212** [comment]
@iG0tB0lts
I think as @DO97 said games like tic-tac-toe have a predetermined path if one knows their way around. Why the original tic tac toe ends up in a draw is because of it being smaller and being a 3x3 grid only, so you only got a certain set of moves. 

With the connect 4 if you know your way around and can predict your opponents moves you can avoid the situation and get a draw. I've done the similar thing with tic-tac-four in a similar way. It's not a flaw of the game but just a mental tactic of a player.

**Comment by iG0tB0lts** [comment]
Thanks for the discussion :+1: . Forgot to close the issue !
